# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# ENV['FIREBASE_DEV_APP_ID'] = "1:1029715426511:android:9de739fc7d5e22e7258bba"
# ENV['FIREBASE_APP_ID'] = "1:1029715426511:android:5608bf9f81cea9da258bba"

default_platform(:android)

platform :android do
	
	desc "Lane for distributing a staging application using Firebase App Distribution"
	lane :staging do
        gradle(task: "clean assembleDevelopmentRelease")
        firebase_app_distribution(
            service_credentials_file: "firebase_credentials.json",
            app: "1:1029715426511:android:9de739fc7d5e22e7258bba",
            release_notes_file: "FirebaseAppDistributionConfig/release_notes.txt",
            groups_file: "FirebaseAppDistributionConfig/groups.txt"
        )
	end

	desc "Lane for distributing a production application using Firebase App Distribution"
	lane :production do
        gradle(task: "clean assembleProductionRelease")
        firebase_app_distribution(
            service_credentials_file: "firebase_credentials.json",
            app: "1:1029715426511:android:5608bf9f81cea9da258bba",
            release_notes_file: "FirebaseAppDistributionConfig/release_notes.txt",
            groups_file: "FirebaseAppDistributionConfig/groups.txt"
        )
	end

end
